//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Data.Objects;
using System.Data.Objects.DataClasses;
using System.Data.EntityClient;
using System.ComponentModel;
using System.Xml.Serialization;
using System.Runtime.Serialization;

[assembly: EdmSchemaAttribute()]

namespace WpfApplication1
{
    #region Contexts
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    public partial class Zalora_AppEntities1 : ObjectContext
    {
        #region Constructors
    
        /// <summary>
        /// Initializes a new Zalora_AppEntities1 object using the connection string found in the 'Zalora_AppEntities1' section of the application configuration file.
        /// </summary>
        public Zalora_AppEntities1() : base("name=Zalora_AppEntities1", "Zalora_AppEntities1")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new Zalora_AppEntities1 object.
        /// </summary>
        public Zalora_AppEntities1(string connectionString) : base(connectionString, "Zalora_AppEntities1")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new Zalora_AppEntities1 object.
        /// </summary>
        public Zalora_AppEntities1(EntityConnection connection) : base(connection, "Zalora_AppEntities1")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        #endregion
    
        #region Partial Methods
    
        partial void OnContextCreated();
    
        #endregion
    
    }
    

    #endregion
    
    
}
